// frontend/src/views/admin/AuditLog.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { useI18n } from 'vue-i18n'

import { adminAuditApi, type AdminAction, type ListAuditParams } from '@/api/admin/audit'
import EmptyState from '@/components/common/EmptyState.vue'
import Skeleton from '@/components/common/Skeleton.vue'
import { formatError } from '@/utils/format'

const { t } = useI18n()

const rows = ref<AdminAction[]>([])
const loading = ref(true)
const error = ref<string | null>(null)

const filters = ref<ListAuditParams>({ limit: 100 })

async function reload() {
  loading.value = true
  error.value = null
  try {
    const { actions } = await adminAuditApi.list(filters.value)
    rows.value = actions
  } catch (e: any) {
    error.value = formatError(e, t('admin.auditLog.loadFailed'))
  } finally {
    loading.value = false
  }
}

// Debounced refresh on filter typing so we don't fire a request
// per keystroke.
let debounceTimer: ReturnType<typeof setTimeout> | null = null
watch(
  () => [filters.value.username, filters.value.resource, filters.value.method],
  () => {
    if (debounceTimer) clearTimeout(debounceTimer)
    debounceTimer = setTimeout(reload, 300)
  },
)

function statusChip(code: number): string {
  if (code >= 200 && code < 300)
    return 'bg-accent-50 text-accent-700 ring-accent-100 dark:bg-accent-950/40 dark:text-accent-300 dark:ring-accent-800'
  if (code >= 400 && code < 500)
    return 'bg-amber-50 text-amber-700 ring-amber-100 dark:bg-amber-950/40 dark:text-amber-300 dark:ring-amber-800'
  return 'bg-red-50 text-red-700 ring-red-100 dark:bg-red-950/40 dark:text-red-300 dark:ring-red-800'
}

function methodChip(m: string): string {
  return ({
    GET: 'bg-sky-50 text-sky-700 ring-sky-200 dark:bg-sky-950/40 dark:text-sky-300 dark:ring-sky-800',
    POST: 'bg-emerald-50 text-emerald-700 ring-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:ring-emerald-800',
    PUT: 'bg-amber-50 text-amber-700 ring-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:ring-amber-800',
    DELETE: 'bg-red-50 text-red-700 ring-red-200 dark:bg-red-950/40 dark:text-red-300 dark:ring-red-800',
    PATCH: 'bg-violet-50 text-violet-700 ring-violet-200 dark:bg-violet-950/40 dark:text-violet-300 dark:ring-violet-800',
  } as Record<string, string>)[m] ?? ''
}

const hasFilters = computed(() => !!(filters.value.username || filters.value.resource || filters.value.method))

onMounted(reload)
</script>

<template>
  <div>
    <header class="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
      <div>
        <h1 class="text-2xl font-semibold tracking-tight text-ink-900 dark:text-surface-50">{{ $t('admin.auditLog.title') }}</h1>
        <p class="mt-1.5 text-sm text-surface-500">{{ $t('admin.auditLog.subtitle') }}</p>
      </div>
    </header>

    <!-- Filters -->
    <div class="mb-4 grid grid-cols-1 gap-2 sm:grid-cols-4">
      <input
        v-model="filters.username"
        type="text"
        :placeholder="$t('admin.auditLog.filterUsername')"
        class="rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 text-sm dark:border-surface-700 dark:bg-surface-900"
      />
      <input
        v-model="filters.resource"
        type="text"
        :placeholder="$t('admin.auditLog.filterResource')"
        class="rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 text-sm dark:border-surface-700 dark:bg-surface-900"
      />
      <select
        v-model="filters.method"
        class="rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 text-sm dark:border-surface-700 dark:bg-surface-900"
      >
        <option value="">{{ $t('admin.auditLog.anyMethod') }}</option>
        <option value="POST">POST</option>
        <option value="PUT">PUT</option>
        <option value="DELETE">DELETE</option>
        <option value="PATCH">PATCH</option>
      </select>
      <button
        type="button"
        class="rounded-lg border border-surface-200 px-3 py-2 text-sm font-medium text-surface-700 transition-colors hover:bg-surface-50 dark:border-surface-700 dark:text-surface-300 dark:hover:bg-surface-800"
        @click="reload"
      >
        {{ $t('admin.users.reload') }}
      </button>
    </div>

    <p v-if="error" class="mb-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600 ring-1 ring-inset ring-red-100 dark:bg-red-950/40 dark:text-red-300">{{ error }}</p>

    <Skeleton v-if="loading" :rows="6" />

    <div v-else-if="rows.length > 0" class="overflow-x-auto rounded-2xl border border-surface-100 bg-surface-0 dark:border-surface-800 dark:bg-surface-900">
      <table class="min-w-full text-sm">
        <thead class="text-left text-2xs font-medium uppercase tracking-wider text-surface-400 dark:text-surface-500">
          <tr class="border-b border-surface-100 dark:border-surface-800">
            <th class="px-6 py-3 font-medium">{{ $t('admin.auditLog.column.time') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.auditLog.column.admin') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.auditLog.column.method') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.auditLog.column.path') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.auditLog.column.target') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.auditLog.column.status') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.auditLog.column.ip') }}</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-surface-100 dark:divide-surface-800">
          <tr v-for="r in rows" :key="r.id" class="transition-colors hover:bg-surface-50/60 dark:hover:bg-surface-800/40">
            <td class="px-6 py-3.5 font-mono text-xs text-surface-500 whitespace-nowrap">{{ new Date(r.created_at).toLocaleString() }}</td>
            <td class="px-6 py-3.5 font-medium text-ink-900 dark:text-surface-50">{{ r.admin_username || $t('admin.auditLog.unknownAdmin') }}</td>
            <td class="px-6 py-3.5">
              <span class="inline-flex items-center rounded-md px-2 py-0.5 text-2xs font-medium ring-1 ring-inset" :class="methodChip(r.method)">{{ r.method }}</span>
            </td>
            <td class="px-6 py-3.5 font-mono text-xs text-surface-600 dark:text-surface-300 break-all">{{ r.path }}<span v-if="r.query_string" class="text-surface-400">?{{ r.query_string }}</span></td>
            <td class="px-6 py-3.5 text-xs">
              <span v-if="r.target_resource" class="font-mono">{{ r.target_resource }}{{ r.target_id ? ' #' + r.target_id : '' }}</span>
              <span v-else class="text-surface-400">—</span>
            </td>
            <td class="px-6 py-3.5">
              <span class="inline-flex items-center rounded-full px-2 py-0.5 text-2xs font-medium ring-1 ring-inset" :class="statusChip(r.status_code)">{{ r.status_code }}</span>
              <div v-if="r.error_msg" class="mt-1 max-w-xs truncate text-2xs text-red-600">{{ r.error_msg }}</div>
            </td>
            <td class="px-6 py-3.5 font-mono text-2xs text-surface-500">{{ r.ip || '—' }}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <EmptyState
      v-else
      icon="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4"
      :title="$t('admin.auditLog.emptyTitle')"
      :description="hasFilters ? $t('admin.auditLog.emptyFiltered') : $t('admin.auditLog.emptyTotal')"
    />
  </div>
</template>

// frontend/src/views/admin/AuditLog.tsx
import { Card, Input, Select, Space, Tag, Typography } from 'antd'
import type { ColumnsType, TableProps } from 'antd/es/table'
import { useEffect, useMemo, useRef, useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { AdminAction, ListAuditParams } from '@/api/admin/audit'
import { ConfigListPage, RefreshButton } from '@/components/common'
import { useAuditLog } from '@/hooks/queries/admin/audit'

type SortKey = 'created_at' | 'admin_username' | 'method' | 'status_code'

const METHODS = ['POST', 'PUT', 'DELETE', 'PATCH'] as const

function formatDate(value: string) {
  return new Date(value).toLocaleString()
}

function methodTag(method: string) {
  const colorByMethod: Record<string, string> = {
    GET: 'blue',
    POST: 'green',
    PUT: 'gold',
    DELETE: 'red',
    PATCH: 'purple',
  }

  return <Tag color={colorByMethod[method] ?? 'default'}>{method}</Tag>
}

function statusTag(code: number) {
  if (code >= 200 && code < 300) {
    return <Tag color="green">{code}</Tag>
  }
  if (code >= 400 && code < 500) {
    return <Tag color="gold">{code}</Tag>
  }
  return <Tag color="red">{code}</Tag>
}

function compareRows(a: AdminAction, b: AdminAction, key: SortKey) {
  if (key === 'status_code') {
    return a.status_code - b.status_code
  }

  return String(a[key] ?? '').localeCompare(String(b[key] ?? ''))
}

export default function AuditLog() {
  const { t } = useTranslation()
  const [username, setUsername] = useState('')
  const [resource, setResource] = useState('')
  const [method, setMethod] = useState<string | undefined>()
  const [debouncedFilters, setDebouncedFilters] = useState<ListAuditParams>({ limit: 100 })
  const mounted = useRef(false)

  useEffect(() => {
    if (!mounted.current) {
      mounted.current = true
      return undefined
    }

    const timer = window.setTimeout(() => {
      setDebouncedFilters({
        limit: 100,
        username: username.trim() || undefined,
        resource: resource.trim() || undefined,
        method,
      })
    }, 300)

    return () => window.clearTimeout(timer)
  }, [method, resource, username])

  const auditQuery = useAuditLog(debouncedFilters)
  const rows = auditQuery.data?.actions ?? []
  const hasFilters = Boolean(debouncedFilters.username || debouncedFilters.resource || debouncedFilters.method)

  const columns: ColumnsType<AdminAction> = useMemo(
    () => [
      {
        title: t('admin.auditLog.column.time'),
        dataIndex: 'created_at',
        align: 'center',
        className: 'table-cell-nowrap',
        width: 180,
        sorter: (a, b) => compareRows(a, b, 'created_at'),
        defaultSortOrder: 'descend',
        render: formatDate,
      },
      {
        title: t('admin.auditLog.column.admin'),
        dataIndex: 'admin_username',
        sorter: (a, b) => compareRows(a, b, 'admin_username'),
        render: (value: string) => value || t('admin.auditLog.unknownAdmin'),
      },
      {
        title: t('admin.auditLog.column.method'),
        dataIndex: 'method',
        align: 'center',
        width: 110,
        sorter: (a, b) => compareRows(a, b, 'method'),
        render: methodTag,
      },
      {
        title: t('admin.auditLog.column.path'),
        dataIndex: 'path',
        render: (path: string, row) => (
          <Typography.Text code>
            {path}
            {row.query_string ? `?${row.query_string}` : ''}
          </Typography.Text>
        ),
      },
      {
        title: t('admin.auditLog.column.target'),
        key: 'target',
        render: (_, row) =>
          row.target_resource ? (
            <Typography.Text code>
              {row.target_resource}
              {row.target_id ? ` #${row.target_id}` : ''}
            </Typography.Text>
          ) : (
            <Typography.Text type="secondary">-</Typography.Text>
          ),
      },
      {
        title: t('admin.auditLog.column.status'),
        dataIndex: 'status_code',
        align: 'center',
        width: 130,
        sorter: (a, b) => compareRows(a, b, 'status_code'),
        render: (code: number, row) => (
          <Space direction="vertical" size={2}>
            {statusTag(code)}
            {row.error_msg ? <Typography.Text type="danger">{row.error_msg}</Typography.Text> : null}
          </Space>
        ),
      },
      {
        title: t('admin.auditLog.column.ip'),
        dataIndex: 'ip',
        align: 'center',
        className: 'table-cell-nowrap',
        width: 140,
        render: (ip: string) => ip || '-',
      },
    ],
    [t],
  )

  const onTableChange: TableProps<AdminAction>['onChange'] = () => undefined

  return (
    <section className="admin-audit-log-page">
      <ConfigListPage
        title={t('admin.auditLog.title')}
        subtitle={t('admin.auditLog.subtitle')}
        actions={<RefreshButton loading={auditQuery.isFetching} onClick={() => auditQuery.refetch()} />}
        filters={
          <Space wrap>
            <Input
              allowClear
              aria-label={t('admin.auditLog.filterUsername')}
              placeholder={t('admin.auditLog.filterUsername')}
              value={username}
              onChange={(event) => setUsername(event.target.value)}
              style={{ width: 240 }}
            />
            <Input
              allowClear
              aria-label={t('admin.auditLog.filterResource')}
              placeholder={t('admin.auditLog.filterResource')}
              value={resource}
              onChange={(event) => setResource(event.target.value)}
              style={{ width: 240 }}
            />
            <Select
              allowClear
              aria-label={t('admin.auditLog.filterMethod')}
              placeholder={t('admin.auditLog.anyMethod')}
              value={method}
              onChange={setMethod}
              style={{ width: 160 }}
              options={METHODS.map((value) => ({ label: value, value }))}
            />
          </Space>
        }
        rowKey="id"
        columns={columns}
        dataSource={rows}
        loading={auditQuery.isLoading}
        pagination={{ pageSize: 20, showSizeChanger: false }}
        onChange={onTableChange}
        emptyState={{
          description: hasFilters ? t('admin.auditLog.emptyFiltered') : t('admin.auditLog.emptyTotal'),
        }}
        mobileCard={(row) => (
          <Card size="small" style={{ width: '100%' }}>
            <Space direction="vertical" size={4}>
              <Typography.Text type="secondary">{formatDate(row.created_at)}</Typography.Text>
              <Typography.Text strong>{row.admin_username || t('admin.auditLog.unknownAdmin')}</Typography.Text>
              <Space wrap>
                {methodTag(row.method)}
                {statusTag(row.status_code)}
              </Space>
              <Typography.Text code>
                {row.path}
                {row.query_string ? `?${row.query_string}` : ''}
              </Typography.Text>
              <Typography.Text>{row.target_resource ? `${row.target_resource} #${row.target_id}` : '-'}</Typography.Text>
              <Typography.Text type="secondary">{row.ip || '-'}</Typography.Text>
            </Space>
          </Card>
        )}
      />
    </section>
  )
}
