// frontend/src/views/admin/Orders.tsx
import { Button, Card, Modal, Segmented, Space, Tag, Typography, message } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'
import type { AdminOrder, OrderStatus } from '@/api/admin/orders'
import type { AdminPlan } from '@/api/admin/plans'
import type { AdminUser } from '@/api/admin/users'
import { ConfigListPage, RefreshButton } from '@/components/common'
import { useOrdersList, useRefundOrder } from '@/hooks/queries/admin/orders'
import { usePlansList } from '@/hooks/queries/admin/plans'
import { useUsersList } from '@/hooks/queries/admin/users'

type StatusFilter = 'all' | OrderStatus

function formatMoney(cents: number) {
  return `¥${(cents / 100).toFixed(2)}`
}

function formatDate(value?: string | null) {
  return value ? new Date(value).toLocaleString() : '-'
}

function canRefund(status: OrderStatus) {
  return status === 'completed' || status === 'paid'
}

function statusTag(status: OrderStatus, label: string = status) {
  const colorByStatus: Record<OrderStatus, string> = {
    completed: 'green',
    paid: 'green',
    failed: 'red',
    refunded: 'gold',
    created: 'default',
  }

  return <Tag color={colorByStatus[status]}>{label}</Tag>
}

function asMap<T extends { id: number }>(items: T[] = []) {
  return new Map(items.map((item) => [item.id, item]))
}

export default function Orders() {
  const { t } = useTranslation()
  const [statusFilter, setStatusFilter] = useState<StatusFilter>('all')

  const ordersQuery = useOrdersList({ limit: 200 })
  const plansQuery = usePlansList()
  const usersQuery = useUsersList({ limit: 500 })
  const refundOrder = useRefundOrder()

  const orders = useMemo(() => ordersQuery.data?.orders ?? [], [ordersQuery.data])
  const plansById = useMemo(() => asMap<AdminPlan>(plansQuery.data ?? []), [plansQuery.data])
  const usersById = useMemo(() => asMap<AdminUser>(usersQuery.data?.users ?? []), [usersQuery.data])

  const filteredOrders = useMemo(() => {
    const visible = statusFilter === 'all' ? orders : orders.filter((order) => order.status === statusFilter)
    return [...visible].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
  }, [orders, statusFilter])

  const stats = useMemo(() => {
    const paidOrders = orders.filter((order) => order.status === 'completed' || order.status === 'paid')
    return {
      total: orders.length,
      completed: paidOrders.length,
      revenue: paidOrders.reduce((sum, order) => sum + order.price_cents, 0),
    }
  }, [orders])

  const loading = ordersQuery.isLoading || plansQuery.isLoading || usersQuery.isLoading
  const refreshing = ordersQuery.isFetching || plansQuery.isFetching || usersQuery.isFetching

  const planName = (id: number) => plansById.get(id)?.name ?? t('admin.stats.unknownPlan', { id })
  const userEmail = (id: number) => usersById.get(id)?.email ?? t('admin.stats.unknownUser', { id })
  const statusLabel = (status: OrderStatus) => t(`admin.orders.status.${status}`)
  const statusTagLabel = (status: OrderStatus) => t('admin.orders.statusTag', { status: statusLabel(status) })
  const statusFilters: Array<{ label: string; value: StatusFilter }> = [
    { label: t('admin.orders.filterAll'), value: 'all' },
    { label: statusLabel('completed'), value: 'completed' },
    { label: t('admin.stats.orderStatus.paid'), value: 'paid' },
    { label: statusLabel('failed'), value: 'failed' },
    { label: statusLabel('refunded'), value: 'refunded' },
    { label: statusLabel('created'), value: 'created' },
  ]

  const refresh = () => {
    ordersQuery.refetch()
    plansQuery.refetch()
    usersQuery.refetch()
  }

  const confirmRefund = (order: AdminOrder) => {
    Modal.confirm({
      title: t('admin.orders.refundTitle'),
      content: t('admin.orders.refundConfirmMsg', {
        amount: formatMoney(order.price_cents),
        email: userEmail(order.user_id),
        id: order.id,
        plan: planName(order.plan_id),
      }),
      okText: t('admin.orders.refund'),
      okButtonProps: { danger: true },
      onOk: async () => {
        await refundOrder.mutateAsync({ id: order.id, reason: 'admin manual refund' })
        message.success(t('admin.orders.status.refunded'))
      },
    })
  }

  const columns: ColumnsType<AdminOrder> = [
    {
      title: t('admin.orders.column.orderId'),
      dataIndex: 'id',
      align: 'center',
      width: 96,
      render: (id: number) => <Typography.Text code>#{id}</Typography.Text>,
    },
    {
      title: t('admin.orders.column.user'),
      dataIndex: 'user_id',
      render: (id: number) => (
        <Space direction="vertical" size={0}>
          <Typography.Text>{userEmail(id)}</Typography.Text>
          <Typography.Text type="secondary">{t('admin.stats.unknownUser', { id })}</Typography.Text>
        </Space>
      ),
    },
    {
      title: t('admin.orders.column.plan'),
      dataIndex: 'plan_id',
      render: (id: number) => planName(id),
    },
    {
      title: t('admin.orders.column.amount'),
      dataIndex: 'price_cents',
      align: 'right',
      className: 'table-cell-number',
      width: 120,
      render: formatMoney,
    },
    {
      title: t('admin.orders.column.status'),
      dataIndex: 'status',
      align: 'center',
      width: 150,
      render: (status: OrderStatus, order) => (
        <Space direction="vertical" size={2}>
          {statusTag(status, statusTagLabel(status))}
          {order.error_message ? <Typography.Text type="danger">{order.error_message}</Typography.Text> : null}
        </Space>
      ),
    },
    {
      title: t('admin.orders.column.created'),
      dataIndex: 'created_at',
      align: 'center',
      className: 'table-cell-nowrap',
      width: 180,
      sorter: (a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime(),
      defaultSortOrder: 'descend',
      render: formatDate,
    },
    {
      title: t('admin.orders.column.completed'),
      dataIndex: 'completed_at',
      align: 'center',
      className: 'table-cell-nowrap',
      width: 180,
      render: formatDate,
    },
    {
      title: t('admin.users.column.actions'),
      key: 'actions',
      align: 'center',
      className: 'table-cell-actions',
      width: 120,
      render: (_, order) =>
        canRefund(order.status) ? (
          <Button
            danger
            size="small"
            loading={refundOrder.isPending && refundOrder.variables?.id === order.id}
            onClick={() => confirmRefund(order)}
          >
            {t('admin.orders.refund')}
          </Button>
        ) : null,
    },
  ]

  return (
    <section>
      <ConfigListPage
        title={t('admin.orders.title')}
        subtitle={t('admin.orders.subtitle')}
        actions={<RefreshButton loading={refreshing} onClick={refresh} label={t('admin.orders.reload')} />}
        stats={
          <div style={{ display: 'grid', gap: 12, gridTemplateColumns: 'repeat(auto-fit, minmax(160px, 1fr))' }}>
            <Card size="small">
              <Typography.Text type="secondary">{t('admin.orders.kpiTotal')}</Typography.Text>
              <Typography.Title level={3} style={{ margin: 0 }}>
                {stats.total}
              </Typography.Title>
            </Card>
            <Card size="small">
              <Typography.Text type="secondary">{t('admin.orders.kpiCompleted')}</Typography.Text>
              <Typography.Title level={3} style={{ margin: 0 }}>
                {stats.completed}
              </Typography.Title>
            </Card>
            <Card size="small">
              <Typography.Text type="secondary">{t('admin.orders.kpiRevenue')}</Typography.Text>
              <Typography.Title level={3} style={{ margin: 0 }}>
                {formatMoney(stats.revenue)}
              </Typography.Title>
            </Card>
          </div>
        }
        filters={
          <Segmented
            options={statusFilters}
            value={statusFilter}
            onChange={(value) => setStatusFilter(value as StatusFilter)}
          />
        }
        rowKey="id"
        columns={columns}
        dataSource={filteredOrders}
        loading={loading}
        pagination={{ pageSize: 20, showSizeChanger: false }}
        emptyState={{
          title: t('admin.orders.empty'),
          description: orders.length === 0 ? t('admin.orders.emptyDescriptionTotal') : t('admin.orders.emptyDescriptionFiltered'),
        }}
        mobileCard={(order) => (
          <Card size="small" style={{ width: '100%' }}>
            <Space direction="vertical" size={4}>
              <Space wrap>
                <Typography.Text code>#{order.id}</Typography.Text>
                {statusTag(order.status, statusTagLabel(order.status))}
              </Space>
              <Typography.Text strong>{planName(order.plan_id)}</Typography.Text>
              <Typography.Text>{userEmail(order.user_id)}</Typography.Text>
              <Typography.Text>{formatMoney(order.price_cents)}</Typography.Text>
              <Typography.Text type="secondary">{formatDate(order.created_at)}</Typography.Text>
              {canRefund(order.status) ? (
                <Button
                  danger
                  size="small"
                  loading={refundOrder.isPending && refundOrder.variables?.id === order.id}
                  onClick={() => confirmRefund(order)}
                >
                  {t('admin.orders.refund')}
                </Button>
              ) : null}
            </Space>
          </Card>
        )}
      />
    </section>
  )
}

// frontend/src/views/admin/Orders.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import { adminOrdersApi, type AdminOrder } from '@/api/admin/orders'
import { adminPlansApi, type AdminPlan } from '@/api/admin/plans'
import { adminUsersApi, type AdminUser } from '@/api/admin/users'
import ConfirmModal from '@/components/common/ConfirmModal.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import Skeleton from '@/components/common/Skeleton.vue'
import { useConfirm } from '@/composables/useConfirm'
import { formatError } from '@/utils/format'

const { t } = useI18n()

const { state: confirmState, ask: askConfirm, settle: settleConfirm } = useConfirm()

const orders = ref<AdminOrder[]>([])
const plansById = ref<Map<number, AdminPlan>>(new Map())
const usersById = ref<Map<number, AdminUser>>(new Map())
const loading = ref(true)
const error = ref<string | null>(null)
const statusFilter = ref<'all' | AdminOrder['status']>('all')

async function reload() {
  loading.value = true
  error.value = null
  try {
    const [o, p, u] = await Promise.all([
      adminOrdersApi.list({ limit: 200 }),
      adminPlansApi.list(),
      adminUsersApi.list({ limit: 500 }),
    ])
    orders.value = o.orders
    plansById.value = new Map(p.map(plan => [plan.id, plan]))
    usersById.value = new Map(u.users.map(user => [user.id, user]))
  } catch (e: any) {
    error.value = formatError(e, t('admin.orders.loadFailed'))
  } finally {
    loading.value = false
  }
}

function planName(id: number): string {
  return plansById.value.get(id)?.name ?? `Plan #${id}`
}
function userEmail(id: number): string {
  return usersById.value.get(id)?.email ?? `User #${id}`
}
function formatYuan(cents: number): string {
  return '¥' + (cents / 100).toFixed(2)
}

function statusPill(s: string): { cls: string; label: string } {
  switch (s) {
    case 'completed':
    case 'paid':
      return { cls: 'bg-accent-50 text-accent-700 ring-accent-100 dark:bg-accent-950/40 dark:text-accent-300 dark:ring-accent-800', label: t('admin.orders.status.completed') }
    case 'failed':
      return { cls: 'bg-red-50 text-red-600 ring-red-100 dark:bg-red-950/40 dark:text-red-300 dark:ring-red-800', label: t('admin.orders.status.failed') }
    case 'refunded':
      return { cls: 'bg-amber-50 text-amber-700 ring-amber-100 dark:bg-amber-950/40 dark:text-amber-300 dark:ring-amber-800', label: t('admin.orders.status.refunded') }
    case 'created':
      return { cls: 'bg-surface-100 text-surface-600 ring-surface-200 dark:bg-surface-800 dark:text-surface-300 dark:ring-surface-700', label: t('admin.orders.status.created') }
    default:
      return { cls: 'bg-surface-100 text-surface-500', label: s }
  }
}

const filtered = computed(() => {
  const list = statusFilter.value === 'all'
    ? orders.value
    : orders.value.filter(o => o.status === statusFilter.value)
  return [...list].sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime())
})

const stats = computed(() => {
  const total = orders.value.length
  const completed = orders.value.filter(o => o.status === 'completed' || o.status === 'paid').length
  const revenue = orders.value
    .filter(o => o.status === 'completed' || o.status === 'paid')
    .reduce((s, o) => s + o.price_cents, 0)
  return { total, completed, revenue }
})

// Refund: only completed / paid orders are eligible. Admin can
// provide an optional reason that gets recorded in the user's
// balance-ledger note for the +PriceCents credit.
const refundingId = ref<number | null>(null)
const refundErr = ref<string | null>(null)

async function refund(o: AdminOrder) {
  const ok = await askConfirm({
    title: t('admin.orders.refundTitle'),
    message: t('admin.orders.refundConfirmMsg', {
      id: o.id,
      plan: planName(o.plan_id),
      amount: formatYuan(o.price_cents),
      email: userEmail(o.user_id),
    }),
    variant: 'danger',
    confirmLabel: t('admin.orders.refund'),
  })
  if (!ok) return
  refundingId.value = o.id
  refundErr.value = null
  try {
    const updated = await adminOrdersApi.refund(o.id, 'admin manual refund')
    // Optimistic replace so the user sees the chip flip without a full reload.
    const i = orders.value.findIndex(x => x.id === o.id)
    if (i >= 0) orders.value.splice(i, 1, updated)
  } catch (e: any) {
    refundErr.value = formatError(e, t('admin.orders.refundFailed'))
  } finally {
    refundingId.value = null
  }
}

function refundable(s: string): boolean {
  return s === 'completed' || s === 'paid'
}

onMounted(reload)
</script>

<template>
  <div>
    <header class="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
      <div>
        <h1 class="text-2xl font-semibold tracking-tight text-ink-900 dark:text-surface-50">{{ $t('admin.orders.title') }}</h1>
        <p class="mt-1.5 text-sm text-surface-500">{{ $t('admin.orders.subtitle') }}</p>
      </div>
      <button class="inline-flex h-9 w-9 items-center justify-center rounded-xl border border-surface-200 bg-surface-0 text-surface-600 transition-all ease-brand hover:border-surface-300 hover:bg-surface-50 hover:text-ink-900 active:scale-[0.98] dark:border-surface-700 dark:bg-surface-900 dark:hover:bg-surface-800" :title="$t('admin.orders.reload')" @click="reload">
        <svg class="h-3.5 w-3.5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 12a9 9 0 0 1-15 6.7L3 16" /><path d="M3 12a9 9 0 0 1 15-6.7L21 8" /><path d="M21 3v5h-5" /><path d="M3 21v-5h5" /></svg>
      </button>
    </header>

    <p v-if="error" class="mb-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600 ring-1 ring-inset ring-red-100 dark:bg-red-950/40 dark:text-red-300">{{ error }}</p>

    <!-- Summary stats -->
    <div v-if="!loading && orders.length > 0" class="mb-5 grid grid-cols-3 gap-3">
      <div class="rounded-2xl border border-surface-100 bg-surface-0 p-4 dark:border-surface-800 dark:bg-surface-900">
        <div class="text-2xs font-medium text-surface-500">{{ $t('admin.orders.kpiTotal') }}</div>
        <div class="mt-2 text-lg font-semibold tracking-tight text-ink-900 tabular-nums dark:text-surface-50">{{ stats.total }}</div>
      </div>
      <div class="rounded-2xl border border-surface-100 bg-surface-0 p-4 dark:border-surface-800 dark:bg-surface-900">
        <div class="text-2xs font-medium text-surface-500">{{ $t('admin.orders.kpiCompleted') }}</div>
        <div class="mt-2 text-lg font-semibold tracking-tight text-ink-900 tabular-nums dark:text-surface-50">{{ stats.completed }}</div>
      </div>
      <div class="rounded-2xl border border-surface-100 bg-surface-0 p-4 dark:border-surface-800 dark:bg-surface-900">
        <div class="text-2xs font-medium text-surface-500">{{ $t('admin.orders.kpiRevenue') }}</div>
        <div class="mt-2 text-lg font-semibold tracking-tight text-accent-600 tabular-nums dark:text-accent-400">{{ formatYuan(stats.revenue) }}</div>
      </div>
    </div>

    <!-- Status filter chips -->
    <div v-if="!loading && orders.length > 0" class="mb-4 flex h-9 items-center gap-0.5 rounded-xl border border-surface-200 bg-surface-0 p-1 text-xs dark:border-surface-700 dark:bg-surface-900 w-fit">
      <button v-for="s in ['all','completed','failed','refunded','created'] as const" :key="s" type="button"
        class="rounded-lg px-3 py-1 font-medium transition-all duration-150 ease-brand"
        :class="statusFilter === s ? 'bg-ink-900 text-white shadow-card dark:bg-accent-600' : 'text-surface-500 hover:bg-surface-100 hover:text-ink-900 dark:text-surface-400 dark:hover:bg-surface-800 dark:hover:text-surface-50'"
        @click="statusFilter = s">
        {{ s === 'all' ? $t('admin.orders.filterAll') : statusPill(s).label }}
      </button>
    </div>

    <Skeleton v-if="loading" :rows="6" />

    <div v-else-if="filtered.length > 0" class="overflow-x-auto rounded-2xl border border-surface-100 bg-surface-0 dark:border-surface-800 dark:bg-surface-900">
      <table class="min-w-full text-sm">
        <thead class="text-left text-2xs font-medium uppercase tracking-wider text-surface-400 dark:text-surface-500">
          <tr class="border-b border-surface-100 dark:border-surface-800">
            <th class="px-6 py-3 font-medium">{{ $t('admin.orders.column.orderId') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.orders.column.user') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.orders.column.plan') }}</th>
            <th class="px-6 py-3 text-right font-medium">{{ $t('admin.orders.column.amount') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.orders.column.status') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.orders.column.created') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.orders.column.completed') }}</th>
            <th class="px-6 py-3 text-right font-medium">{{ $t('admin.users.column.actions') }}</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-surface-100 dark:divide-surface-800">
          <tr v-for="o in filtered" :key="o.id" class="transition-colors hover:bg-surface-50/60 dark:hover:bg-surface-800/40">
            <td class="px-6 py-3.5 font-mono text-xs text-surface-400 tabular-nums">#{{ o.id }}</td>
            <td class="px-6 py-3.5">
              <div class="text-sm text-ink-900 dark:text-surface-50">{{ userEmail(o.user_id) }}</div>
              <div class="mt-0.5 font-mono text-2xs text-surface-400">user #{{ o.user_id }}</div>
            </td>
            <td class="px-6 py-3.5 font-medium text-ink-900 dark:text-surface-50">{{ planName(o.plan_id) }}</td>
            <td class="px-6 py-3.5 text-right tabular-nums font-medium text-ink-900 dark:text-surface-50">{{ formatYuan(o.price_cents) }}</td>
            <td class="px-6 py-3.5">
              <span class="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ring-1 ring-inset" :class="statusPill(o.status).cls">{{ statusPill(o.status).label }}</span>
              <div v-if="o.error_message" class="mt-1 text-2xs text-red-600">{{ o.error_message }}</div>
            </td>
            <td class="px-6 py-3.5 text-xs text-surface-500">{{ new Date(o.created_at).toLocaleString() }}</td>
            <td class="px-6 py-3.5 text-xs text-surface-500">{{ o.completed_at ? new Date(o.completed_at).toLocaleString() : '—' }}</td>
            <td class="px-6 py-3.5 text-right">
              <button
                v-if="refundable(o.status)"
                type="button"
                class="rounded-lg border border-amber-200 px-2.5 py-1 text-xs font-medium text-amber-700 transition-colors hover:bg-amber-50 disabled:opacity-50 dark:border-amber-800 dark:text-amber-300 dark:hover:bg-amber-950/40"
                :disabled="refundingId === o.id"
                @click="refund(o)"
              >
                {{ refundingId === o.id ? $t('admin.orders.processing') : $t('admin.orders.refund') }}
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <EmptyState
      v-else
      icon="M3 6h18M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M19 6l-1 14a2 2 0 0 1-2 2H8a2 2 0 0 1-2-2L5 6"
      :title="$t('admin.orders.empty')"
      :description="orders.length === 0 ? $t('admin.orders.emptyDescriptionTotal') : $t('admin.orders.emptyDescriptionFiltered')"
    />

    <p v-if="refundErr" class="mt-3 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600 ring-1 ring-inset ring-red-100 dark:bg-red-950/40 dark:text-red-300 dark:ring-red-800">{{ refundErr }}</p>
    <ConfirmModal
      v-if="confirmState"
      :open="confirmState.open"
      :title="confirmState.title"
      :message="confirmState.message"
      :confirm-label="confirmState.confirmLabel"
      :variant="confirmState.variant"
      @confirm="settleConfirm(true)"
      @cancel="settleConfirm(false)"
    />
  </div>
</template>
