// frontend/src/views/admin/Webhooks.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import {
  adminWebhooksApi,
  type Webhook,
  type WebhookDelivery,
  type WebhookInput,
  type WebhookMethod,
} from '@/api/admin/webhooks'
import ConfirmModal from '@/components/common/ConfirmModal.vue'
import EmptyState from '@/components/common/EmptyState.vue'
import Skeleton from '@/components/common/Skeleton.vue'
import { useConfirm } from '@/composables/useConfirm'
import { formatError } from '@/utils/format'

const props = withDefaults(defineProps<{ embedded?: boolean }>(), {
  embedded: false,
})

const { t } = useI18n()

const { state: confirmState, ask: askConfirm, settle: settleConfirm } = useConfirm()

const rows = ref<Webhook[]>([])
const loading = ref(true)
const error = ref<string | null>(null)

const editor = ref<{
  open: boolean
  mode: 'create' | 'edit'
  id: number | null
  draft: WebhookInput
  busy: boolean
  err: string | null
}>(makeEditor())

function makeEditor() {
  return {
    open: false,
    mode: 'create' as const,
    id: null as number | null,
    draft: blankDraft(),
    busy: false,
    err: null as string | null,
  }
}

function blankDraft(): WebhookInput {
  return {
    name: '',
    url: '',
    events: [],
    enabled: true,
    allow_private: false,
    method: 'POST',
    headers: {},
    body_template: '',
    template_format: 'json',
  }
}

// Headers UI: editable as a flat string `Key: Value` per line; we
// parse on save so admins don't fight a fiddly key-value-pair table.
const headersText = ref('')

function headersToText(h: Record<string, string>): string {
  return Object.entries(h)
    .map(([k, v]) => `${k}: ${v}`)
    .join('\n')
}

function textToHeaders(s: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const line of s.split('\n')) {
    const idx = line.indexOf(':')
    if (idx <= 0) continue
    const k = line.slice(0, idx).trim()
    const v = line.slice(idx + 1).trim()
    if (k) out[k] = v
  }
  return out
}

// Events UI: editable as comma-separated patterns.
const eventsText = ref('')

async function reload() {
  loading.value = true
  error.value = null
  try {
    rows.value = await adminWebhooksApi.list()
  } catch (e: any) {
    error.value = formatError(e, t('admin.webhooks.loadFailed'))
  } finally {
    loading.value = false
  }
}

function openCreate() {
  editor.value = makeEditor()
  editor.value.open = true
  headersText.value = ''
  eventsText.value = '*'
}

function openEdit(w: Webhook) {
  editor.value = {
    open: true,
    mode: 'edit',
    id: w.id,
    draft: {
      name: w.name,
      url: w.url,
      events: w.events,
      enabled: w.enabled,
      allow_private: w.allow_private,
      method: w.method,
      headers: { ...w.headers },
      body_template: w.body_template,
      template_format: w.template_format,
    },
    busy: false,
    err: null,
  }
  headersText.value = headersToText(w.headers)
  eventsText.value = w.events.join(', ')
}

async function save() {
  editor.value.err = null
  editor.value.busy = true
  try {
    editor.value.draft.headers = textToHeaders(headersText.value)
    editor.value.draft.events = eventsText.value
      .split(',')
      .map((s) => s.trim())
      .filter(Boolean)
    if (editor.value.mode === 'create') {
      await adminWebhooksApi.create(editor.value.draft)
    } else if (editor.value.id) {
      await adminWebhooksApi.update(editor.value.id, editor.value.draft)
    }
    editor.value.open = false
    await reload()
  } catch (e: any) {
    editor.value.err = formatError(e, t('admin.webhooks.saveFailed'))
  } finally {
    editor.value.busy = false
  }
}

async function destroy(w: Webhook) {
  const ok = await askConfirm({
    title: t('admin.webhooks.confirmDelete'),
    message: t('admin.webhooks.confirmDeleteMsg', { name: w.name }),
    variant: 'danger',
    confirmLabel: t('admin.webhooks.delete'),
  })
  if (!ok) return
  try {
    await adminWebhooksApi.remove(w.id)
    await reload()
  } catch (e: any) {
    error.value = formatError(e, t('admin.webhooks.deleteFailed'))
  }
}

// Deliveries panel: lazy-fetched per webhook on first expand. The
// underlying endpoint returns the most-recent N rows (server-side
// limit; client just renders what it gets). Closes by re-clicking
// the toggle.
const deliveries = ref<Record<number, WebhookDelivery[]>>({})
const expandedID = ref<number | null>(null)
const deliveriesLoading = ref<number | null>(null)
const deliveriesErr = ref<string | null>(null)

async function toggleDeliveries(w: Webhook) {
  if (expandedID.value === w.id) {
    expandedID.value = null
    return
  }
  expandedID.value = w.id
  if (deliveries.value[w.id]) return // already cached
  deliveriesLoading.value = w.id
  deliveriesErr.value = null
  try {
    deliveries.value[w.id] = await adminWebhooksApi.deliveries(w.id)
  } catch (e: any) {
    deliveriesErr.value = formatError(e, t('admin.webhooks.deliveriesLoadFailed'))
  } finally {
    deliveriesLoading.value = null
  }
}

function deliveryChipClass(status: string): string {
  switch (status) {
    case 'success':
      return 'bg-accent-50 text-accent-700 ring-accent-100 dark:bg-accent-950/40 dark:text-accent-300 dark:ring-accent-800'
    case 'failed':
      return 'bg-red-50 text-red-700 ring-red-100 dark:bg-red-950/40 dark:text-red-300 dark:ring-red-800'
    default:
      return 'bg-amber-50 text-amber-700 ring-amber-100 dark:bg-amber-950/40 dark:text-amber-300 dark:ring-amber-800'
  }
}

// Per-row pending state so admin sees "test 中…" feedback while
// the call is in flight, and a transient flash on completion.
const testBusy = ref<number | null>(null)
const testFlash = ref<{ id: number; kind: 'ok' | 'err'; text: string } | null>(null)

async function testFire(w: Webhook) {
  testBusy.value = w.id
  testFlash.value = null
  try {
    await adminWebhooksApi.test(w.id)
    testFlash.value = { id: w.id, kind: 'ok', text: t('admin.webhooks.testSent') }
    // Auto-expand the deliveries panel + refresh — admin almost
    // always wants to see the result of the test fire, not just
    // a "sent" confirmation.
    deliveries.value[w.id] = await adminWebhooksApi.deliveries(w.id)
    expandedID.value = w.id
  } catch (e: any) {
    testFlash.value = { id: w.id, kind: 'err', text: formatError(e, t('admin.webhooks.testFailed')) }
  } finally {
    testBusy.value = null
    // Auto-clear after 4s so the table doesn't accumulate stale notices.
    setTimeout(() => {
      if (testFlash.value?.id === w.id) testFlash.value = null
    }, 4000)
  }
}

// Per-row state for the replay action on individual delivery rows.
const replayBusy = ref<number | null>(null)
const replayErr = ref<string | null>(null)

async function replayDelivery(w: Webhook, deliveryID: number) {
  replayBusy.value = deliveryID
  replayErr.value = null
  try {
    await adminWebhooksApi.replay(deliveryID)
    // Refresh the deliveries list so admin sees the new attempt row.
    deliveries.value[w.id] = await adminWebhooksApi.deliveries(w.id)
  } catch (e: any) {
    replayErr.value = formatError(e, t('admin.webhooks.replayFailed'))
  } finally {
    replayBusy.value = null
  }
}

function chipForMethod(m: WebhookMethod): string {
  return ({
    GET: 'bg-sky-50 text-sky-700 ring-sky-200 dark:bg-sky-950/40 dark:text-sky-300 dark:ring-sky-800',
    POST: 'bg-emerald-50 text-emerald-700 ring-emerald-200 dark:bg-emerald-950/40 dark:text-emerald-300 dark:ring-emerald-800',
    PUT: 'bg-amber-50 text-amber-700 ring-amber-200 dark:bg-amber-950/40 dark:text-amber-300 dark:ring-amber-800',
    DELETE: 'bg-red-50 text-red-700 ring-red-200 dark:bg-red-950/40 dark:text-red-300 dark:ring-red-800',
    PATCH: 'bg-violet-50 text-violet-700 ring-violet-200 dark:bg-violet-950/40 dark:text-violet-300 dark:ring-violet-800',
  } as Record<string, string>)[m] ?? ''
}

onMounted(reload)
</script>

<template>
  <div>
    <header
      :class="[
        'flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between',
        props.embedded ? 'mb-4' : 'mb-7',
      ]"
    >
      <div>
        <component
          :is="props.embedded ? 'h4' : 'h1'"
          :class="[
            'font-semibold tracking-tight text-ink-900 dark:text-surface-50',
            props.embedded ? 'text-base' : 'text-2xl',
          ]"
        >
          {{ props.embedded ? $t('admin.webhooks.embeddedTitle') : $t('admin.webhooks.title') }}
        </component>
        <p class="mt-1.5 text-sm text-surface-500 dark:text-surface-400">{{ $t('admin.webhooks.subtitle') }}</p>
      </div>
      <button
        type="button"
        class="inline-flex h-9 items-center gap-1.5 rounded-xl bg-ink-900 px-3.5 text-sm font-medium text-white shadow-card transition-all ease-brand hover:bg-ink-800 active:scale-[0.98] dark:bg-accent-600 dark:hover:bg-accent-500"
        @click="openCreate"
      >
        <svg class="h-4 w-4 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round">
          <path d="M12 5v14M5 12h14" />
        </svg>
        {{ $t('admin.webhooks.createNew') }}
      </button>
    </header>

    <p v-if="error" class="mb-4 rounded-xl bg-red-50 px-4 py-3 text-sm text-red-600 ring-1 ring-inset ring-red-100 dark:bg-red-950/40 dark:text-red-300">{{ error }}</p>

    <Skeleton v-if="loading" :rows="4" />

    <div v-else-if="rows.length > 0" class="overflow-x-auto rounded-2xl border border-surface-100 bg-surface-0 dark:border-surface-800 dark:bg-surface-900">
      <table class="min-w-full text-sm">
        <thead class="text-left text-xs font-semibold uppercase tracking-wider text-surface-500 dark:text-surface-400">
          <tr class="border-b border-surface-100 dark:border-surface-800">
            <th class="px-6 py-3 font-medium">{{ $t('admin.webhooks.column.name') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.webhooks.column.method') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.webhooks.column.url') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.webhooks.column.events') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.webhooks.column.template') }}</th>
            <th class="px-6 py-3 font-medium">{{ $t('admin.webhooks.column.status') }}</th>
            <th class="px-6 py-3 text-right font-medium">{{ $t('admin.webhooks.column.actions') }}</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-surface-100 dark:divide-surface-800">
          <template v-for="w in rows" :key="w.id">
          <tr class="transition-colors hover:bg-surface-50/60 dark:hover:bg-surface-800/40">
            <td class="px-6 py-3.5 font-medium text-ink-900 dark:text-surface-50">{{ w.name }}</td>
            <td class="px-6 py-3.5">
              <span class="inline-flex items-center rounded-md px-2 py-0.5 text-2xs font-medium ring-1 ring-inset" :class="chipForMethod(w.method)">{{ w.method }}</span>
            </td>
            <td class="px-6 py-3.5 font-mono text-xs text-surface-600 dark:text-surface-300">{{ w.url }}</td>
            <td class="px-6 py-3.5 font-mono text-2xs text-surface-500">{{ w.events.join(', ') || '*' }}</td>
            <td class="px-6 py-3.5 text-2xs text-surface-500">
              {{ w.body_template ? `${w.template_format} • ${w.body_template.length} chars` : `default (${w.template_format})` }}
            </td>
            <td class="px-6 py-3.5">
              <span v-if="w.enabled" class="inline-flex items-center rounded-full bg-accent-50 px-2 py-0.5 text-xs font-medium text-accent-700 ring-1 ring-inset ring-accent-100 dark:bg-accent-950/40 dark:text-accent-300 dark:ring-accent-800">{{ $t('admin.webhooks.enabled') }}</span>
              <span v-else class="inline-flex items-center rounded-full bg-surface-100 px-2 py-0.5 text-xs font-medium text-surface-500 ring-1 ring-inset ring-surface-200 dark:bg-surface-800 dark:text-surface-400 dark:ring-surface-700">{{ $t('admin.webhooks.disabled') }}</span>
            </td>
            <td class="px-6 py-3.5 text-right">
              <div class="inline-flex items-center gap-1">
                <button class="rounded-lg border border-surface-200 px-2.5 py-1 text-xs font-medium text-surface-700 transition-colors hover:bg-surface-50 dark:border-surface-700 dark:text-surface-300 dark:hover:bg-surface-800" type="button" @click="toggleDeliveries(w)">{{ expandedID === w.id ? $t('admin.webhooks.collapse') : $t('admin.webhooks.deliveries') }}</button>
                <button
                  type="button"
                  class="rounded-lg border border-surface-200 px-2.5 py-1 text-xs font-medium text-surface-700 transition-colors hover:bg-surface-50 disabled:opacity-50 dark:border-surface-700 dark:text-surface-300 dark:hover:bg-surface-800"
                  :disabled="testBusy === w.id"
                  @click="testFire(w)"
                >
                  {{ testBusy === w.id ? $t('admin.webhooks.testSending') : $t('admin.webhooks.test') }}
                </button>
                <span
                  v-if="testFlash && testFlash.id === w.id"
                  class="ml-1 text-2xs"
                  :class="testFlash.kind === 'ok' ? 'text-accent-600' : 'text-red-600'"
                >
                  {{ testFlash.text }}
                </span>
                <button class="rounded-lg border border-surface-200 px-2.5 py-1 text-xs font-medium text-surface-700 transition-colors hover:bg-surface-50 dark:border-surface-700 dark:text-surface-300 dark:hover:bg-surface-800" type="button" @click="openEdit(w)">{{ $t('admin.webhooks.edit') }}</button>
                <button class="rounded-lg border border-red-200 px-2.5 py-1 text-xs font-medium text-red-700 transition-colors hover:bg-red-50 dark:border-red-800 dark:text-red-300 dark:hover:bg-red-950/40" type="button" @click="destroy(w)">{{ $t('admin.webhooks.delete') }}</button>
              </div>
            </td>
          </tr>
          <!-- Expanded deliveries subrow — fetched lazily on first
               "记录" click, cached after that. Shows the N most-recent
               attempts for this webhook so admin can verify the
               receiver is actually getting hit. -->
          <tr v-if="expandedID === w.id">
            <td colspan="7" class="bg-surface-50/60 px-6 py-4 dark:bg-surface-800/40">
              <div v-if="deliveriesLoading === w.id" class="text-xs text-surface-500">{{ $t('admin.webhooks.deliveriesLoading') }}</div>
              <p v-else-if="deliveriesErr" class="text-xs text-red-600">{{ deliveriesErr }}</p>
              <div v-else-if="deliveries[w.id]?.length === 0" class="text-xs text-surface-500">{{ $t('admin.webhooks.deliveriesEmpty') }}</div>
              <div v-else class="space-y-1.5">
                <p v-if="replayErr" class="text-2xs text-red-600">{{ replayErr }}</p>
                <div
                  v-for="d in deliveries[w.id]"
                  :key="d.id"
                  class="grid grid-cols-[auto_1fr_auto_auto_auto] items-center gap-3 rounded-lg border border-surface-100 bg-surface-0 px-3 py-1.5 text-2xs dark:border-surface-700 dark:bg-surface-900"
                >
                  <span class="inline-flex items-center rounded-full px-1.5 py-0.5 font-medium ring-1 ring-inset" :class="deliveryChipClass(d.status)">{{ d.status }}</span>
                  <span class="font-mono text-surface-600 dark:text-surface-300">{{ d.event_type }}</span>
                  <span class="font-mono text-surface-500">attempt {{ d.attempt }} · HTTP {{ d.http_status || '—' }}</span>
                  <span class="font-mono text-surface-400">{{ new Date(d.scheduled_at).toLocaleString() }}</span>
                  <button
                    type="button"
                    class="rounded border border-surface-200 px-1.5 py-0.5 font-medium text-surface-600 hover:bg-surface-50 disabled:opacity-50 dark:border-surface-700 dark:text-surface-300 dark:hover:bg-surface-800"
                    :disabled="replayBusy === d.id"
                    @click="replayDelivery(w, d.id)"
                  >
                    {{ replayBusy === d.id ? $t('admin.webhooks.replayBusy') : $t('admin.webhooks.replay') }}
                  </button>
                  <p v-if="d.error" class="col-span-5 truncate font-mono text-red-600">err: {{ d.error }}</p>
                </div>
              </div>
            </td>
          </tr>
          </template>
        </tbody>
      </table>
    </div>

    <EmptyState
      v-else
      icon="M13 10V3L4 14h7v7l9-11h-7z"
      :title="$t('admin.webhooks.empty')"
      :description="$t('admin.webhooks.emptyDescription')"
    />

    <!-- Editor modal -->
    <div
      v-if="editor.open"
      class="fixed inset-0 z-50 flex items-center justify-center bg-ink-900/50 p-4"
      @click.self="editor.open = false"
    >
      <div class="flex max-h-[90vh] w-full max-w-3xl flex-col overflow-hidden rounded-2xl bg-surface-0 shadow-elevated dark:bg-surface-900">
        <header class="flex items-center justify-between border-b border-surface-100 px-6 py-4 dark:border-surface-800">
          <h2 class="text-lg font-semibold">{{ editor.mode === 'create' ? $t('admin.webhooks.createTitle') : $t('admin.webhooks.editTitle', { id: editor.id }) }}</h2>
          <button type="button" class="rounded p-1 text-surface-400 hover:bg-surface-100 hover:text-surface-700 dark:hover:bg-surface-800" @click="editor.open = false">
            <svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6 6 18M6 6l12 12" /></svg>
          </button>
        </header>

        <form class="flex-1 space-y-4 overflow-y-auto px-6 py-5" @submit.prevent="save">
          <div class="grid grid-cols-2 gap-3">
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-surface-600 dark:text-surface-300">{{ $t('admin.webhooks.name') }}</span>
              <input v-model="editor.draft.name" type="text" required class="w-full rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 text-sm dark:border-surface-700 dark:bg-surface-900" />
            </label>
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-surface-600 dark:text-surface-300">{{ $t('admin.webhooks.methodChip') }}</span>
              <select v-model="editor.draft.method" class="w-full rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 text-sm dark:border-surface-700 dark:bg-surface-900">
                <option value="POST">POST</option>
                <option value="GET">GET</option>
                <option value="PUT">PUT</option>
                <option value="DELETE">DELETE</option>
                <option value="PATCH">PATCH</option>
              </select>
            </label>
          </div>

          <label class="block">
            <span class="mb-1 block text-xs font-medium text-surface-600 dark:text-surface-300">URL</span>
            <input v-model="editor.draft.url" type="url" required class="w-full rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 font-mono text-sm dark:border-surface-700 dark:bg-surface-900" :placeholder="$t('admin.webhooks.urlPlaceholder')" />
          </label>

          <label class="block">
            <span class="mb-1 block text-xs font-medium text-surface-600 dark:text-surface-300">
              {{ $t('admin.webhooks.eventsLabel') }}
            </span>
            <input v-model="eventsText" type="text" class="w-full rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 font-mono text-sm dark:border-surface-700 dark:bg-surface-900" :placeholder="$t('admin.webhooks.eventsPlaceholder')" />
            <span class="mt-1 block text-2xs text-surface-500">
              {{ $t('admin.webhooks.eventsCommon') }}
            </span>
          </label>

          <div class="grid grid-cols-2 gap-3">
            <label class="block">
              <span class="mb-1 block text-xs font-medium text-surface-600 dark:text-surface-300">{{ $t('admin.webhooks.bodyFormat') }}</span>
              <select v-model="editor.draft.template_format" class="w-full rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 text-sm dark:border-surface-700 dark:bg-surface-900">
                <option value="json">{{ $t('admin.webhooks.bodyFormatOpts.json') }}</option>
                <option value="form">{{ $t('admin.webhooks.bodyFormatOpts.form') }}</option>
                <option value="text">{{ $t('admin.webhooks.bodyFormatOpts.text') }}</option>
                <option value="raw">{{ $t('admin.webhooks.bodyFormatOpts.raw') }}</option>
              </select>
            </label>
            <div class="flex items-end gap-4">
              <label class="flex items-center gap-2 text-sm">
                <input v-model="editor.draft.enabled" type="checkbox" class="h-4 w-4 rounded border-surface-300" />
                {{ $t('admin.webhooks.enabledCheckbox') }}
              </label>
              <label class="flex items-center gap-2 text-sm">
                <input v-model="editor.draft.allow_private" type="checkbox" class="h-4 w-4 rounded border-surface-300" />
                {{ $t('admin.webhooks.privateAllowed') }}
              </label>
            </div>
          </div>

          <label class="block">
            <span class="mb-1 block text-xs font-medium text-surface-600 dark:text-surface-300">
              {{ $t('admin.webhooks.body') }}
            </span>
            <textarea v-model="editor.draft.body_template" rows="6" class="w-full rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 font-mono text-xs dark:border-surface-700 dark:bg-surface-900" :placeholder="$t('admin.webhooks.bodyPlaceholder')" />
            <p class="mt-1 text-2xs text-surface-500">{{ $t('admin.webhooks.bodyVars') }}</p>
          </label>

          <label class="block">
            <span class="mb-1 block text-xs font-medium text-surface-600 dark:text-surface-300">{{ $t('admin.webhooks.headersLabel') }}</span>
            <textarea v-model="headersText" rows="3" class="w-full rounded-lg border border-surface-200 bg-surface-0 px-3 py-2 font-mono text-xs dark:border-surface-700 dark:bg-surface-900" :placeholder="$t('admin.webhooks.headersPlaceholder')" />
          </label>

          <p v-if="editor.err" class="rounded-lg bg-red-50 px-3 py-2 text-xs text-red-600 ring-1 ring-inset ring-red-100 dark:bg-red-950/40 dark:text-red-300">{{ editor.err }}</p>

          <div class="flex justify-end gap-2 border-t border-surface-100 pt-4 dark:border-surface-800">
            <button type="button" class="rounded-lg border border-surface-200 px-4 py-2 text-sm font-medium text-surface-700 hover:bg-surface-50 dark:border-surface-700 dark:text-surface-300 dark:hover:bg-surface-800" @click="editor.open = false">{{ $t('admin.webhooks.cancel') }}</button>
            <button type="submit" :disabled="editor.busy" class="rounded-lg bg-ink-900 px-4 py-2 text-sm font-medium text-white hover:bg-ink-800 disabled:opacity-60 dark:bg-accent-600 dark:hover:bg-accent-500">
              {{ editor.busy ? $t('admin.webhooks.saving') : $t('admin.webhooks.save') }}
            </button>
          </div>
        </form>
      </div>
    </div>

    <ConfirmModal
      v-if="confirmState"
      :open="confirmState.open"
      :title="confirmState.title"
      :message="confirmState.message"
      :confirm-label="confirmState.confirmLabel"
      :variant="confirmState.variant"
      @confirm="settleConfirm(true)"
      @cancel="settleConfirm(false)"
    />
  </div>
</template>

// frontend/src/views/admin/Webhooks.tsx
import {
  DeleteOutlined,
  EditOutlined,
  ExperimentOutlined,
  PlusOutlined,
  RetweetOutlined,
} from '@ant-design/icons'
import {
  Alert,
  Button,
  Card,
  Descriptions,
  Drawer,
  Empty,
  Form,
  Input,
  Modal,
  Select,
  Space,
  Switch,
  Tag,
  Typography,
  message,
} from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import { adminWebhooksApi, type Webhook, type WebhookDelivery, type WebhookInput, type WebhookMethod } from '@/api/admin/webhooks'
import { ConfigListPage, RefreshButton } from '@/components/common'
import {
  useCreateWebhook,
  useRemoveWebhook,
  useReplayWebhookDelivery,
  useTestWebhook,
  useUpdateWebhook,
  useWebhookDeliveries,
  useWebhooksList,
} from '@/hooks/queries/admin/webhooks'
import {
  blankWebhookInput,
  eventsToText,
  headersToText,
  textToEvents,
  textToHeaders,
  webhookToInput,
} from './webhooks/parse'

interface WebhookFormValues extends Omit<WebhookInput, 'events' | 'headers'> {
  events_text: string
  headers_text: string
}

export interface WebhooksProps {
  embedded?: boolean
}

function inputToForm(input: WebhookInput): WebhookFormValues {
  return {
    ...input,
    events_text: eventsToText(input.events),
    headers_text: headersToText(input.headers),
  }
}

function formToInput(values: WebhookFormValues): WebhookInput {
  return {
    name: values.name.trim(),
    url: values.url.trim(),
    events: textToEvents(values.events_text),
    enabled: values.enabled,
    allow_private: values.allow_private,
    method: values.method,
    headers: textToHeaders(values.headers_text),
    body_template: values.body_template ?? '',
    template_format: values.template_format,
    secret: values.secret?.trim() || undefined,
  }
}

function methodColor(method: WebhookMethod) {
  return {
    DELETE: 'red',
    GET: 'blue',
    PATCH: 'purple',
    POST: 'green',
    PUT: 'gold',
  }[method]
}

function statusColor(status: string) {
  if (status === 'success') return 'green'
  if (status === 'failed') return 'red'
  return 'gold'
}

function deliveryStatusLabel(status: string, t: ReturnType<typeof useTranslation>['t']) {
  return t(`admin.webhooks.deliveryStatus.${status}`, { defaultValue: t('admin.webhooks.deliveryStatus.unknown', { status }) })
}

function DeliveryList({
  deliveries,
  loading,
  replaying,
  onReplay,
}: {
  deliveries: WebhookDelivery[]
  loading: boolean
  replaying?: number
  onReplay: (delivery: WebhookDelivery) => void
}) {
  const { t } = useTranslation()

  if (loading) return <Typography.Text type="secondary">{t('admin.webhooks.deliveriesLoading')}</Typography.Text>
  if (deliveries.length === 0) return <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={t('admin.webhooks.deliveriesEmpty')} />

  return (
    <Space direction="vertical" size={8} style={{ width: '100%' }}>
      {deliveries.map((delivery) => (
        <Card key={delivery.id} size="small" styles={{ body: { padding: 12 } }}>
          <Space align="start" style={{ justifyContent: 'space-between', width: '100%' }}>
            <Space direction="vertical" size={2}>
              <Space wrap>
                <Tag color={statusColor(delivery.status)}>{deliveryStatusLabel(delivery.status, t)}</Tag>
                <Typography.Text code>{delivery.event_type}</Typography.Text>
                <Typography.Text type="secondary">
                  {t('admin.webhooks.deliveryMeta', { attempt: delivery.attempt, status: delivery.http_status || '-' })}
                </Typography.Text>
              </Space>
              <Typography.Text type="secondary">{new Date(delivery.scheduled_at).toLocaleString()}</Typography.Text>
              {delivery.error ? <Typography.Text type="danger">{t('admin.webhooks.deliveryError', { error: delivery.error })}</Typography.Text> : null}
            </Space>
            <Button
              aria-label={t('admin.webhooks.replay')}
              size="small"
              icon={<RetweetOutlined />}
              loading={replaying === delivery.id}
              onClick={() => onReplay(delivery)}
            >
              {t('admin.webhooks.replay')}
            </Button>
          </Space>
        </Card>
      ))}
    </Space>
  )
}

export default function Webhooks({ embedded = false }: WebhooksProps) {
  const { t } = useTranslation()
  const [form] = Form.useForm<WebhookFormValues>()
  const [drawerOpen, setDrawerOpen] = useState(false)
  const [editing, setEditing] = useState<Webhook | null>(null)
  const [expandedID, setExpandedID] = useState<number | null>(null)
  const [deliveryCache, setDeliveryCache] = useState<Record<number, WebhookDelivery[]>>({})
  const [replayingID, setReplayingID] = useState<number>()

  const webhooksQuery = useWebhooksList()
  const deliveriesQuery = useWebhookDeliveries(expandedID ?? 0, expandedID !== null && !deliveryCache[expandedID])
  const createWebhook = useCreateWebhook()
  const updateWebhook = useUpdateWebhook()
  const removeWebhook = useRemoveWebhook()
  const testWebhook = useTestWebhook()
  const replayDelivery = useReplayWebhookDelivery()

  const webhooks = webhooksQuery.data ?? []
  const saving = createWebhook.isPending || updateWebhook.isPending
  const error =
    webhooksQuery.error ??
    createWebhook.error ??
    updateWebhook.error ??
    removeWebhook.error ??
    testWebhook.error ??
    replayDelivery.error

  const visibleDeliveries = expandedID ? deliveryCache[expandedID] ?? deliveriesQuery.data ?? [] : []

  useEffect(() => {
    if (expandedID && deliveriesQuery.data && !deliveryCache[expandedID]) {
      setDeliveryCache((current) => ({ ...current, [expandedID]: deliveriesQuery.data ?? [] }))
    }
  }, [deliveriesQuery.data, deliveryCache, expandedID])

  const openCreate = () => {
    setEditing(null)
    form.setFieldsValue(inputToForm(blankWebhookInput()))
    setDrawerOpen(true)
  }

  const openEdit = (webhook: Webhook) => {
    setEditing(webhook)
    form.setFieldsValue(inputToForm(webhookToInput(webhook)))
    setDrawerOpen(true)
  }

  const closeDrawer = () => {
    setDrawerOpen(false)
    setEditing(null)
    form.resetFields()
  }

  const submit = async () => {
    const values = await form.validateFields().catch(() => null)
    if (!values) return

    let payload: WebhookInput
    try {
      payload = formToInput(values)
    } catch (err) {
      form.setFields([
        {
          name: 'headers_text',
          errors: [err instanceof Error ? err.message : t('admin.webhooks.invalidHeaders')],
        },
      ])
      return
    }

    if (editing) {
      await updateWebhook.mutateAsync({ id: editing.id, patch: payload })
    } else {
      await createWebhook.mutateAsync(payload)
    }
    closeDrawer()
  }

  const toggleDeliveries = (webhook: Webhook) => {
    setExpandedID((current) => (current === webhook.id ? null : webhook.id))
  }

  const refreshDeliveries = async (webhookID: number) => {
    const rows = await adminWebhooksApi.deliveries(webhookID)
    setDeliveryCache((current) => ({ ...current, [webhookID]: rows }))
  }

  const fireTest = async (webhook: Webhook) => {
    await testWebhook.mutateAsync(webhook.id)
    setExpandedID(webhook.id)
    setDeliveryCache((current) => {
      const next = { ...current }
      delete next[webhook.id]
      return next
    })
    await refreshDeliveries(webhook.id)
    message.success(t('admin.webhooks.testSent'))
  }

  const replay = async (webhookID: number, delivery: WebhookDelivery) => {
    setReplayingID(delivery.id)
    try {
      await replayDelivery.mutateAsync(delivery.id)
      setDeliveryCache((current) => {
        const next = { ...current }
        delete next[webhookID]
        return next
      })
      await refreshDeliveries(webhookID)
      message.success(t('admin.webhooks.replayQueued'))
    } finally {
      setReplayingID(undefined)
    }
  }

  const confirmDelete = (webhook: Webhook) => {
    Modal.confirm({
      title: t('admin.webhooks.confirmDelete'),
      content: t('admin.webhooks.confirmDeleteMsg', { name: webhook.name }),
      okText: t('admin.webhooks.delete'),
      okButtonProps: { danger: true },
      onOk: () => removeWebhook.mutateAsync(webhook.id),
    })
  }

  const refresh = () => {
    webhooksQuery.refetch()
    if (expandedID) {
      setDeliveryCache((current) => {
        const next = { ...current }
        delete next[expandedID]
        return next
      })
      deliveriesQuery.refetch()
    }
  }

  const columns: ColumnsType<Webhook> = [
    {
      title: t('admin.webhooks.column.name'),
      dataIndex: 'name',
      render: (_value, webhook) => (
        <Space direction="vertical" size={2}>
          <Typography.Text strong>{webhook.name}</Typography.Text>
          <Typography.Text code copyable>
            {webhook.url}
          </Typography.Text>
        </Space>
      ),
    },
    {
      title: t('admin.webhooks.column.method'),
      dataIndex: 'method',
      width: 100,
      render: (method: WebhookMethod) => <Tag color={methodColor(method)}>{method}</Tag>,
    },
    {
      title: t('admin.webhooks.column.events'),
      dataIndex: 'events',
      render: (events: string[]) => <Typography.Text code>{events.join(', ') || '*'}</Typography.Text>,
    },
    {
      title: t('admin.webhooks.column.template'),
      key: 'template',
      render: (_value, webhook) =>
        webhook.body_template
          ? t('admin.webhooks.templateCustom', { format: webhook.template_format, n: webhook.body_template.length })
          : t('admin.webhooks.templateDefault', { format: webhook.template_format }),
    },
    {
      title: t('admin.webhooks.column.status'),
      dataIndex: 'enabled',
      render: (enabled: boolean) => <Tag color={enabled ? 'green' : 'default'}>{enabled ? t('admin.webhooks.enabled') : t('admin.webhooks.disabled')}</Tag>,
    },
    {
      title: t('admin.webhooks.column.actions'),
      key: 'actions',
      align: 'right',
      render: (_value, webhook) => (
        <Space wrap>
          <Button size="small" onClick={() => toggleDeliveries(webhook)}>
            {expandedID === webhook.id ? t('admin.webhooks.collapse') : t('admin.webhooks.deliveries')}
          </Button>
          <Button
            aria-label={t('admin.webhooks.test')}
            size="small"
            icon={<ExperimentOutlined />}
            loading={testWebhook.isPending}
            onClick={() => fireTest(webhook)}
          >
            {t('admin.webhooks.test')}
          </Button>
          <Button aria-label={t('admin.webhooks.editNamed', { name: webhook.name })} size="small" icon={<EditOutlined />} onClick={() => openEdit(webhook)} />
          <Button
            aria-label={t('admin.webhooks.deleteNamed', { name: webhook.name })}
            danger
            size="small"
            icon={<DeleteOutlined />}
            onClick={() => confirmDelete(webhook)}
          />
        </Space>
      ),
    },
  ]

  return (
    <div>
      <ConfigListPage
        title={embedded ? undefined : t('admin.webhooks.title')}
        subtitle={embedded ? undefined : t('admin.webhooks.subtitle')}
        actions={
          embedded ? undefined : (
            <>
              <Button type="primary" aria-label={t('admin.webhooks.createNew')} icon={<PlusOutlined />} onClick={openCreate}>
                {t('admin.webhooks.createNew')}
              </Button>
              <RefreshButton loading={webhooksQuery.isFetching || deliveriesQuery.isFetching} onClick={refresh} />
            </>
          )
        }
        header={
          embedded ? (
            <div style={{ alignItems: 'center', display: 'flex', justifyContent: 'space-between' }}>
              <div>
                <Typography.Title level={4} style={{ margin: 0 }}>
                  {t('admin.webhooks.title')}
                </Typography.Title>
                <Typography.Text type="secondary">{t('admin.webhooks.subtitle')}</Typography.Text>
              </div>
              <Button type="primary" icon={<PlusOutlined />} onClick={openCreate}>
                {t('admin.webhooks.createNew')}
              </Button>
            </div>
          ) : undefined
        }
        alerts={error ? <Alert type="error" showIcon message={t('admin.webhooks.operationFailed')} /> : null}
        rowKey="id"
        columns={columns}
        dataSource={webhooks}
        expandable={{
          expandedRowKeys: expandedID ? [expandedID] : [],
          expandedRowRender: (webhook) => (
            <DeliveryList
              deliveries={expandedID === webhook.id ? visibleDeliveries : []}
              loading={deliveriesQuery.isFetching && expandedID === webhook.id && !deliveryCache[webhook.id]}
              replaying={replayingID}
              onReplay={(delivery) => replay(webhook.id, delivery)}
            />
          ),
          rowExpandable: (webhook) => expandedID === webhook.id,
          showExpandColumn: false,
        }}
        loading={webhooksQuery.isLoading}
        pagination={false}
        emptyState={{
          title: t('admin.webhooks.empty'),
          description: t('admin.webhooks.emptyDescription'),
        }}
        mobileCard={(webhook) => (
          <Card size="small" style={{ width: '100%' }}>
            <Space direction="vertical" size={8} style={{ width: '100%' }}>
              <Space style={{ justifyContent: 'space-between', width: '100%' }}>
                <Typography.Text strong>{webhook.name}</Typography.Text>
                <Tag color={webhook.enabled ? 'green' : 'default'}>
                  {webhook.enabled ? t('admin.webhooks.enabled') : t('admin.webhooks.disabled')}
                </Tag>
              </Space>
              <Typography.Text code>{webhook.url}</Typography.Text>
              <Descriptions size="small" column={1}>
                <Descriptions.Item label={t('admin.webhooks.column.method')}>{webhook.method}</Descriptions.Item>
                <Descriptions.Item label={t('admin.webhooks.column.events')}>{webhook.events.join(', ') || '*'}</Descriptions.Item>
              </Descriptions>
              <Space wrap>
                <Button size="small" onClick={() => toggleDeliveries(webhook)}>
                  {t('admin.webhooks.deliveries')}
                </Button>
                <Button aria-label={t('admin.webhooks.test')} size="small" icon={<ExperimentOutlined />} onClick={() => fireTest(webhook)}>
                  {t('admin.webhooks.test')}
                </Button>
                <Button size="small" icon={<EditOutlined />} onClick={() => openEdit(webhook)}>
                  {t('admin.webhooks.edit')}
                </Button>
                <Button size="small" danger icon={<DeleteOutlined />} onClick={() => confirmDelete(webhook)}>
                  {t('admin.webhooks.delete')}
                </Button>
              </Space>
            </Space>
          </Card>
        )}
      />

      <Drawer
        title={editing ? t('admin.webhooks.editTitle', { id: editing.id }) : t('admin.webhooks.createTitle')}
        open={drawerOpen}
        width={720}
        destroyOnClose
        onClose={closeDrawer}
        extra={
          <Space>
            <Button onClick={closeDrawer}>{t('admin.webhooks.cancel')}</Button>
            <Button type="primary" loading={saving} onClick={submit}>
              {t('admin.webhooks.save')}
            </Button>
          </Space>
        }
      >
        <Form form={form} layout="vertical" initialValues={inputToForm(blankWebhookInput())}>
          <Form.Item name="name" label={t('admin.webhooks.name')} rules={[{ required: true, message: t('admin.webhooks.nameRequired') }]}>
            <Input />
          </Form.Item>
          <Form.Item name="url" label="URL" rules={[{ required: true, type: 'url', message: t('admin.webhooks.urlRequired') }]}>
            <Input placeholder={t('admin.webhooks.urlPlaceholder')} />
          </Form.Item>
          <Space style={{ width: '100%' }} align="start">
            <Form.Item name="method" label={t('admin.webhooks.column.method')} style={{ width: 180 }}>
              <Select
                options={(['POST', 'GET', 'PUT', 'DELETE', 'PATCH'] as WebhookMethod[]).map((value) => ({
                  label: value,
                  value,
                }))}
              />
            </Form.Item>
            <Form.Item name="template_format" label={t('admin.webhooks.bodyFormat')} style={{ width: 180 }}>
              <Select
                options={['json', 'form', 'text', 'raw'].map((value) => ({
                  label: t(`admin.webhooks.bodyFormatOpts.${value}`),
                  value,
                }))}
              />
            </Form.Item>
          </Space>
          <Form.Item name="events_text" label={t('admin.webhooks.eventsLabel')} extra={t('admin.webhooks.eventsCommon')}>
            <Input placeholder={t('admin.webhooks.eventsPlaceholder')} />
          </Form.Item>
          <Form.Item name="body_template" label={t('admin.webhooks.body')} extra={t('admin.webhooks.bodyVars')}>
            <Input.TextArea rows={6} placeholder={t('admin.webhooks.bodyPlaceholder')} />
          </Form.Item>
          <Form.Item name="headers_text" label={t('admin.webhooks.headersLabel')}>
            <Input.TextArea rows={4} placeholder={t('admin.webhooks.headersPlaceholder')} />
          </Form.Item>
          <Space size={24}>
            <Form.Item name="enabled" label={t('admin.webhooks.enabledCheckbox')} valuePropName="checked">
              <Switch />
            </Form.Item>
            <Form.Item name="allow_private" label={t('admin.webhooks.privateAllowed')} valuePropName="checked">
              <Switch />
            </Form.Item>
          </Space>
        </Form>
      </Drawer>
    </div>
  )
}
